config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

from main.apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
    path('', index, name="index"),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('product_item/<int:pk>/', ProductDetailView.as_view(), name='product_item'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),

    path('blog/', BlogListView.as_view(), name='blog_list'),

    path('blog_item/<slug>/', BlogDetailView.as_view(), name='blog_item'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),

]


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from datetime import date

from django.db import models
from django.urls import reverse
from django.utils.text import slugify

NULLABLE = {'blank':True, 'null': True}
class Product(models.Model):

    product_name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.CharField(max_length=150, verbose_name='Описание')
    product_image = models.ImageField(upload_to='product_image/', verbose_name='Изображение', **NULLABLE)
    product_category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    product_price = models.IntegerField(default=None,verbose_name='Цена за покупку', **NULLABLE)
    date_of_creation = models.DateField(default=date.today, verbose_name='Дата создания')
    date_of_change = models.DateField(default=date.today, verbose_name='Дата последнего изменения')
    is_active = models.BooleanField(default=True, verbose_name='Есть на складе')

    def __str__(self):
        return f'{self.product_name} : {self.description} : {self.product_image} {self.product_category} {self.product_price} {self.date_of_creation} {self.date_of_change}'


# функция переопределяет удаление и не удаляет объект а переводит флаг is_active = False
    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()


    class Meta:
        verbose_name='продукция'
        verbose_name_plural='продукции'
        ordering = ('product_category', )

class Category(models.Model):
    product_category = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.CharField(max_length=150, verbose_name='Описание')
    is_active = models.BooleanField(default=True, verbose_name='Активные категории')

    def __str__(self):
        return f'{self.product_category} : {self.description}'

    class Meta:
        verbose_name='категория'
        verbose_name_plural='категории'
        ordering = ('product_category', )



class Blog(models.Model):
    slug = models.CharField(max_length=250, null=False, unique=True, verbose_name='slug')
    message_preview = models.ImageField(upload_to='message_preview/', verbose_name='Превью', **NULLABLE)
    message_heading = models.CharField(max_length=250, verbose_name='Заголовок')
    message_content= models.TextField(verbose_name='Контент', **NULLABLE)
    date_of_creation = models.DateField(default=date.today, verbose_name='Дата создания')
    date_of_change = models.DateField(default=date.today, verbose_name='Дата последнего изменения')
    is_publication = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0,verbose_name='Количество просмотров')
    user_name = models.CharField(max_length=250,  **NULLABLE, verbose_name='Пользователи')



    def __str__(self):
        return f'{self.message_heading} : {self.message_content}'

        # функция переопределения slug
    def get_absolute_url(self):
        return reverse('blog_item', kwargs={'slug': self.slug})  # new


    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.message_heading)
            self.save()
        return super().save(*args, **kwargs)




    # функция переопределяет удаление и не удаляет объект а переводит флаг is_publication = False
    def delete(self, *args, **kwargs):
            self.is_publication = False
            self.save()

    class Meta:
        verbose_name='Запись блога'
        verbose_name_plural='Записи блога'
        ordering = ('message_heading', )


# class Users(models.Model):
#     user_name = models.CharField(max_length=150, verbose_name='Имя')
#     user_lastname = models.CharField(max_length=150, verbose_name='Отчество')
#     user_surname = models.CharField(max_length=150, verbose_name='Фамилия')
#     user_email = models.EmailField(verbose_name='email', unique=True)
#
#     def __str__(self):
#         return f'{self.user_name} : {self.user_lastname} : {self.user_surname} : {self.user_email}'
#
#     class Meta:
#         verbose_name = 'Пользователь'
#         verbose_name_plural = 'Пользователи'
#         ordering = ('user_name',)

main/views.py
import random

from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main.models import Product, Category, Blog


# Create your views here.




def index(request):
    product_list = Product.objects.all().order_by('?')[:6]
    context = {
        'object_list': product_list,
        'title': 'первые 6 случайных продуктов'
    }
    return render(request, 'main/index.html', context=context)


class ProductListView(ListView):
    model=Product
    extra_context = {
        'title': 'Список продуктов'
    }

# Метод переопределяет представление и выводит только продукты с атрибутом is_active=True)
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset



# def products(request):
#     context = {
#         'object_list': Product.objects.all(),
#         'title': 'Список продуктов'
#     }
#     return render(request, 'main/product_list.html', context=context)

class CategoryListView(ListView):
    model=Category
    extra_context = {
        'title': 'Список категорий'
    }



# def category(request):
#     context = {
#         'object_list': Category.objects.all(),
#         'title': 'Список категорий'
#     }
#
#     return render(request, 'main/category_list.html', context=context)


class ProductDetailView(DetailView):
    model=Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data( **kwargs)
        context_data['title'] = context_data['object'].product_name
        return context_data


# def product_detail(request, pk):
#     product_item = Product.objects.get(pk=pk),
#     context = {
#         'object': product_item[0],
#         'title': product_item[0].product_name
#
#     }
#     return render(request, 'main/product_detail.html', context=context)


class ProductCreateView(CreateView):
    model=Product
    fields = ('product_category', 'product_name', 'description', 'product_price',)
    success_url = reverse_lazy('main:product_list')

class ProductUpdateView(UpdateView):
    model=Product
    fields = ('product_category', 'product_name', 'description', 'product_price',)
    success_url = reverse_lazy('main:product_list')

class ProductDeleteView (DeleteView ):
    model=Product
    success_url = reverse_lazy('main:product_list')


# def product_card(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         phone = request.POST.get('phone')
#         message = request.POST.get('message')
#         print(f'User {name} with phone {phone}- send message: {message}')
#     return render(request, 'main/product_detail.html')

class BlogListView(ListView):
    model=Blog
    extra_context = {
        'title': 'Список постов'
    }

# Метод переопределяет представление и выводит только продукты с атрибутом is_active=True)
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_publication=True)
        return queryset

# class UsersListView(ListView):
#     model=Users
#     extra_context = {
#         'title': 'Список пользователей'
#     }

class BlogDetailView(DetailView):
    model=Blog
    success_url = reverse_lazy('main:blog_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data( **kwargs)
        context_data['title'] = context_data['object'].message_heading
        return context_data

    # Обновлени счетчика просмотрове
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.views_count += 1
        self.object.save()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)




class BlogCreateView(CreateView):
    model=Blog
    fields = ('message_heading', 'message_content', 'message_preview', 'is_publication',)
    success_url = reverse_lazy('main:blog_list')






class BlogUpdateView(UpdateView):
    model=Blog
    fields = ('message_heading', 'message_content', 'message_preview', 'is_publication',)

    # Получаем данные объекта и выводим ту же страницу
    def get_success_url(self) -> str:
        return reverse_lazy('main:blog_update', kwargs={'pk': self.object.pk})

class BlogDeleteView (DeleteView ):
    model=Blog
    success_url = reverse_lazy('main:blog_list')

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">

<header data-bs-theme="dark">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

      <a class="navbar-brand" href="#">Skymarket</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            {% include 'main/includes/inc_main_menu.html' %}

          </div><!-- /.collapse navbar-collapse -->
  </nav>

      <div class="card-body">
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <h1 class="display-4">Skymarket</h1>
                <p class="lead">Skymarket - это отличный вариант для шопинга</p>
            </div>
    </div><!-- /.card-body -->
</header>

<body>

  <div class="card-body">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div><!-- /.row -->
 </div><!-- /.card-body -->
</body>

<div class="b-example-divider"></div>

<div class="b-example-divider"></div>

<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2023 Skymarket, Inc</p>
  </footer>
</div>

<div class="b-example-divider"></div>

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"  >
<script src="{% static 'js/bootstrap.bundle.min.js' %}"  ></script>


</html>

main/templates/main/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="card m-2 text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
        </div>

        <div class="container">
                 <div class="card-body">

                     <form method="post">
                        {% csrf_token %}
                        Уверен что нужно удалить пост "{{ object.message_heading|title }}"?


                </div>
            <div class="card-footer">
                <input type="submit" class="btn btn-outline-danger" value="Подтвердить удаление" >
                <a href="{% url 'main:blog_list' %}" class = "btn btn-primary"> <<Назад</a>
        </div>

    </div>
 {% endblock %}

main/templates/main/blog_form.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="card m-2 text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
        </div>

        <div class="container">
                 <div class="card-body">

                     <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                    <input type="submit" class="btn btn-success" value="{% if object %}Сохранить{% else %}Создать{% endif %}" >

                </div>
            <div class="card-footer">
                    <a href="{% url 'main:blog_list' %}" class = "btn btn-primary"> <<Назад</a>
        </div>

    </div>
 {% endblock %}

main/templates/main/blog_list.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
    </div>

    <diov class="col-12">
        <div class="card-footer">
            <a href="{% url 'main:blog_create' %}" class = "btn btn-primary"> Создать заметку</a>
        </div><!-- /.card-footer -->
    </diov>

{% for object in object_list %}

    <div class="col-lg-4">

              <div class="card m-2 text-center">
                      {% include 'main/includes/inc_blog_card.html' %}
              </div><!-- /.card m-2 text-center -->
    </div><!-- /.col-lg-4 -->
{% endfor  %}
{% endblock %}

main/templates/main/category.html
{% extends 'main/base.html' %}

{% block content %}

     <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->
 <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
 </div>

{% for object in object_list %}
      <div class="col-lg-4">
              <div class="card m-2 text-center">
                      <div class="card-body">
                              {% include 'main/includes/inc_category_card.html' %}

                      </div><!-- /.card-body -->
              </div><!-- /.card m-2 text-center -->
      </div><!-- /.col-lg-4 -->
{% endfor  %}
{% endblock %}

main/templates/main/category_list.html
{% extends 'main/base.html' %}

{% block content %}

     <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->
 <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
 </div>

{% for object in object_list %}
      <div class="col-lg-4">
              <div class="card m-2 text-center">
                      <div class="card-body">
                              {% include 'main/includes/inc_category_card.html' %}

                      </div><!-- /.card-body -->
              </div><!-- /.card m-2 text-center -->
      </div><!-- /.col-lg-4 -->
{% endfor  %}
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

     <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->
 <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
 </div>

{% for object in object_list %}
      <div class="col-lg-4">
              <div class="card m-2 text-center">
                      <div class="card-body">
                              {% include 'main/includes/inc_category_card.html' %}

                      </div><!-- /.card-body -->
              </div><!-- /.card m-2 text-center -->
      </div><!-- /.col-lg-4 -->
{% endfor  %}
{% endblock %}

main/templates/main/post_reqest.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
 {% endblock %}

main/templates/main/product_card.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="card m-2 text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
        </div>

        <div class="container">
                 <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Категория</td>
                            <td>{{object.product_category|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Имя</td>
                            <td>{{object.product_name|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Описание</td>
                            <td>{{object.description|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Прайс</td>
                            <td>{{object.product_price|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Дата создания</td>
                            <td>{{object.date_of_creation|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Дата последнего изменения</td>
                            <td>{{object.date_of_change|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Есть на складе</td>
                            <td>{{object.is_active|title}}</td>
                        </tr>

                    </table>
                </div>
                <div class="card-footer">
                    <a href="{% url 'main:products' %}" class = "btn btn-primary"> <<Назад</a>
        </div>

    </div>
 {% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="card m-2 text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
        </div>

        <div class="container">
                 <div class="card-body">

                     <form method="post">
                        {% csrf_token %}
                        Уверен что нужно удалить продукт "{{ object.product_name }}"?


                </div>
            <div class="card-footer">
                <input type="submit" class="btn btn-outline-danger" value="Подтвердить удаление" >
                <a href="{% url 'main:product_list' %}" class = "btn btn-primary"> <<Назад</a>
        </div>

    </div>
 {% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="card m-2 text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
        </div>

        <div class="container">
                 <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Категория</td>
                            <td>{{object.product_category|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Имя</td>
                            <td>{{object.product_name|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Описание</td>
                            <td>{{object.description|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес файла картинки</td>
                            <td>{{object.product_image}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Прайс</td>
                            <td>{{object.product_price|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Дата создания</td>
                            <td>{{object.date_of_creation|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Дата последнего изменения</td>
                            <td>{{object.date_of_change|title}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Есть на складе</td>
                            <td>{{object.is_active|title}}</td>
                        </tr>

                    </table>
                </div>
                <div class="card-footer">
                    <a href="{% url 'main:product_list' %}" class = "btn btn-primary"> <<Назад</a>
        </div>

    </div>
 {% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
    </div>

    <diov class="col-12">
        <div class="card-footer">
            <a href="{% url 'main:product_create' %}" class = "btn btn-primary"> Создать продукт</a>
        </div><!-- /.card-footer -->
    </diov>

{% for object in object_list %}

    <div class="col-lg-4">

              <div class="card m-2 text-center">
                      {% include 'main/includes/inc_product_card.html' %}
              </div><!-- /.card m-2 text-center -->
    </div><!-- /.col-lg-4 -->
{% endfor  %}
{% endblock %}

main/templates/main/product_load.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
 {% endblock %}

main/templates/main/users_list.html
{% extends 'main/base.html' %}

{% block content %}

     <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->
 <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{title|title}}</h1>
 </div>

{% for object in object_list %}
      <div class="col-lg-4">
              <div class="card m-2 text-center">
                      <div class="card-body">
                              {% include 'main/includes/inc_category_card.html' %}

                      </div><!-- /.card-body -->
              </div><!-- /.card m-2 text-center -->
      </div><!-- /.col-lg-4 -->
{% endfor  %}
{% endblock %}